<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ru.beykerykt.lightapi</groupId>
    <artifactId>LightAPI-parent</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <properties>
        <maven.install.skip>true</maven.install.skip>
    </properties>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <version>3.1.1</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.10.1</version> <!-- Latest version -->
            </plugin>
        </plugins>
    </build>
<modules>
    <module>common</module>
    <module>nms/v1_14_R1</module>
    <module>nms/v1_15_R1</module>
    <module>nms/v1_16_R1</module>
    <module>nms/v1_17_R1</module>
    <module>nms/v1.18_R1</module>
    <module>nms/v26_1_R1</module>
    <module>plugin</module>
</modules>
    <distributionManagement>
        <repository>
            <id>github</id>
            <url>https://maven.pkg.github.com/IMrMDX/LightAPI-Reborn</url>
        </repository>
    </distributionManagement>

</project>
