<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ru.beykerykt</groupId>
    <artifactId>LightAPI-Reborn</artifactId>
    <version>1.0.1</version>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <repositories>
        <repository>
            <id>spigot-repos</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
    </repositories>
    <dependencies>
        <dependency>
            <groupId>ru.beykerykt.lightapi</groupId>
            <artifactId>common</artifactId>
            <version>3.3.0</version>
        </dependency>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.21.4-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20231013</version>
        </dependency>
             <dependency>
                      <groupId>ru.beykerykt.lightapi.nms</groupId>
                      <artifactId>26_1_R1</artifactId>
                      <version>3.3.0</version>
                      <scope>compile</scope>
             </dependency>
<!--        <dependency>-->
<!--            <groupId>ru.beykerykt.lightapi.nms</groupId>-->
<!--            <artifactId>17_R1</artifactId>-->
<!--            <version>3.3.0</version>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>ru.beykerykt.lightapi.nms</groupId>-->
<!--            <artifactId>v1_16_R3</artifactId>-->
<!--            <version>3.3.0</version>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>ru.beykerykt.lightapi.nms</groupId>-->
<!--            <artifactId>v1_16_R2</artifactId>-->
<!--            <version>3.3.0</version>-->
<!--        </dependency>-->
        <dependency>
            <groupId>ru.beykerykt.lightapi.nms</groupId>
            <artifactId>v1_16_R1</artifactId>
            <version>3.3.0</version>
        </dependency>
        <dependency>
            <groupId>ru.beykerykt.lightapi.nms</groupId>
            <artifactId>v1_15_R1</artifactId>
            <version>3.3.0</version>
        </dependency>
        <dependency>
            <groupId>ru.beykerykt.lightapi.nms</groupId>
            <artifactId>v1_14_R1</artifactId>
            <version>3.3.0</version>
        </dependency>
        <dependency>
            <groupId>ru.beykerykt.lightapi.nms</groupId>
            <artifactId>18_R1</artifactId>
            <version>3.3.0</version>
        </dependency>
        <dependency>
            <groupId>ru.beykerykt.lightapi.nms</groupId>
            <artifactId>17_R1</artifactId>
            <version>3.3.0</version>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>ru.beykerykt.lightapi.nms</groupId>-->
<!--            <artifactId>v1_13_R2</artifactId>-->
<!--            <version>3.3.0</version>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>ru.beykerykt.lightapi.nms</groupId>-->
<!--            <artifactId>v1_13_R1</artifactId>-->
<!--            <version>3.3.0</version>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>ru.beykerykt.lightapi.nms</groupId>-->
<!--            <artifactId>v1_12_R1</artifactId>-->
<!--            <version>3.3.0</version>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>ru.beykerykt.lightapi.nms</groupId>-->
<!--            <artifactId>v1_11_R1</artifactId>-->
<!--            <version>3.3.0</version>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>ru.beykerykt.lightapi.nms</groupId>-->
<!--            <artifactId>v1_10_R1</artifactId>-->
<!--            <version>3.3.0</version>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>ru.beykerykt.lightapi.nms</groupId>-->
<!--            <artifactId>v1_9_R2</artifactId>-->
<!--            <version>3.3.0</version>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>ru.beykerykt.lightapi.nms</groupId>-->
<!--            <artifactId>v1_9_R1</artifactId>-->
<!--            <version>3.3.0</version>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>ru.beykerykt.lightapi.nms</groupId>-->
<!--            <artifactId>v1_8_R3</artifactId>-->
<!--            <version>3.3.0</version>-->
<!--        </dependency>-->
    </dependencies>

    <build>
        <resources>
            <resource>
                <filtering>true</filtering>
                <directory>src/main/resources</directory>
                <includes>
                    <include>plugin.yml</include>
                </includes>
            </resource>
            <resource>
                <directory>${project.basedir}/..</directory>
                <includes>
                    <include>LICENSE</include>
                </includes>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <include>config.yml</include>
                </includes>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.1.2</version>
                <configuration>
                    <archive>
                        <addMavenDescriptor>false</addMavenDescriptor>
                        <manifest>
                            <addDefaultEntries>false</addDefaultEntries>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>unpack-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                            <excludeTransitive>true</excludeTransitive>
                            <excludes>META-INF/**</excludes>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
